"""created models for messages and chats, also user route to get all users for now

Revision ID: 3b482accf097
Revises: 
Create Date: 2025-09-02 00:06:29.832786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b482accf097'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE users SET email = CONCAT('temp_', username, '@example.com') WHERE email IS NULL")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
                              existing_type=mysql.VARCHAR(length=100),
                              nullable=False)
        batch_op.alter_column('email',
                              existing_type=mysql.VARCHAR(length=100),
                              nullable=False)
        batch_op.alter_column('password_hash',
                              existing_type=mysql.VARCHAR(length=500),
                              nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
                              existing_type=mysql.VARCHAR(length=500),
                              nullable=True)
        batch_op.alter_column('email',
                              existing_type=mysql.VARCHAR(length=100),
                              nullable=True)
        batch_op.alter_column('username',
                              existing_type=mysql.VARCHAR(length=100),
                              nullable=True)

    # ### end Alembic commands ###
